if(EXISTS "/home/jared/CalculatorSkeleton/calculatorBackend/test/calculator_test[1]_tests.cmake")
  include("/home/jared/CalculatorSkeleton/calculatorBackend/test/calculator_test[1]_tests.cmake")
else()
  add_test(calculator_test_NOT_BUILT calculator_test_NOT_BUILT)
endif()
