version: "3.8"
services:
  app:
      build: .
      restart: always
      volumes:
          - "/angularProject/node_modules"
          - ./:/angularProject
      ports:
          - 4200:4200
      command:
          ng serve --host 0.0.0.0
